print("Enter first list elements")
lst1=list(map(float,input().split()))
print("Enter second list elements")
lst2=list(map(float,input().split()))
#add two list objects by using map()
lst3=list(map(lambda a,b:a+b,lst1,lst2))
print("\tlist1\t\tlist2\t\tsumlist")
for val1,val2,val3 in zip(lst1,lst2,lst3):
    print("\t{}\t\t{}\t\t{}".format(val1,val2,round(val3,2)))
print("-"*50)
